
default_platform(:android)

platform :android do

  desc "Lint check"
  lane :lint do
    gradle(task: "lintDebug")
  end

  desc "Runs Unit tests"
  lane :tests do
    gradle(task: "test")
  end

  desc "Distribute to Firebase"
  lane :beta do
    gradle(task: "clean")
    gradle(
        task: 'assemble',
        build_type: 'Release',
        properties: {
            "maps_api_key_release" => ENV['GOOGLE_MAPS_API']
        }
    )
    firebase_app_distribution(
        service_credentials_file: "distribution_creds.json",
        app: "1:584345545053:android:c80f3617a7a6f5396d20b4",
        groups: "test-group"
    )
   end

end
