
default_platform(:android)

platform :android do

  desc "Lint check"
  lane :lint do
    gradle(task: "lint")
  end

  desc "Runs Unit tests"
  lane :tests do
    gradle(task: "test")
  end

  desc "Distribute to Firebase"
  lane :beta do
    gradle(task: "clean")
    gradle(
        task: 'assemble',
        build_type: 'Release',
        properties: {
            "maps_api_key_release" => ENV['GOOGLE_MAPS_API']
        }
    )
    firebase_app_distribution(
        firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
        app: ENV['FIREBASE_APP_ID'],
        groups: "test-group"
    )
   end

end
