name: Firebase distribute

on: workflow_dispatch

jobs:

  check:
    name: Lint and tests check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ruby setup
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Dependencies
        run: bundle install

      - name: Lint check
        run: fastlane lint

      - name: Upload Lint report
        uses: actions/upload-artifact@v3
        with:
          name: Lint report
          path: app/build/reports/lint-results-debug.html

      - name: Run Unit tests
        run: fastlane tests

      - name: Upload Unit tests report
        uses: actions/upload-artifact@v3
        with:
          name: Unit tests reports
          path: |
            app/build/reports/tests/testDebugUnitTest/
            app/build/reports/tests/testReleaseUnitTest/

  create-doc:
    name: Generate code documentation
    runs-on: ubuntu-latest
    needs: check

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate documentation
        run: ./gradlew dokkaHtml

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: Documentation
          path: app/build/dokka/html/

  distribute:
    name: Distribute to Firebase
    runs-on: ubuntu-latest
    environment: prod
    needs: check

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Ruby setup
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Dependencies
        run: bundle install

      - name: Decode firebase credentials
        run: |
          echo "$FIREBASE_CREDENTIALS" > firebase_credentials.json.b64
          base64 -d -i firebase_credentials.json.b64 > firebase_credentials.json
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}

      - name: Build and distribute
        run: fastlane android beta
        env:
          GOOGLE_MAPS_API: ${{ secrets.GOOGLE_MAPS_API }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALLIAS: ${{ secrets.SIGNING_KEY_ALLIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
