#name: Pull Request check
#
#on:
#  pull_request:
#    branches:
#      - 'dev'
#
#jobs:
#
#  lint-checks:
#    name: Lint check
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#
#      - name: Lint running
#        run: ./gradlew lintDebug
#
#      - name: Upload Lint report
#        uses: actions/upload-artifact@v3
#        with:
#          name: Lint report
#          path: app/build/reports/lint-results-debug.html
#
#  Unit-tests:
#    name: Unit tests running
#    runs-on: ubuntu-latest
#    steps:
#
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#
#      - name: Run Unit tests
#        run: ./gradlew test --stacktrace
#
#      - name: Upload Unit tests report
#        uses: actions/upload-artifact@v3
#        with:
#          name: Unit tests reports
#          path: |
#            app/build/reports/tests/testDebugUnitTest/
#            app/build/reports/tests/testReleaseUnitTest/
#
#  Build-apks:
#    name: Build APKs for Instrumented tests
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#
#      - name: Assemble app
#        run: ./gradlew assembleDebug --stacktrace
#
#      - name: Upload app apk
#        uses: actions/upload-artifact@v3
#        with:
#          name: App apk
#          path: app/build/outputs/apk/debug/app-debug.apk
#
#      - name: Assemble tests
#        run: ./gradlew assembleDebugAndroidTest --stacktrace
#
#      - name: Upload tests apk
#        uses: actions/upload-artifact@v3
#        with:
#          name: Tests apk
#          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
#
#  google-cloud-setup:
#    name: Google Cloud setup
#    runs-on: ubuntu-latest
#    steps:
#      - name: Sign in Google Cloud
#        uses: 'google-github-actions/auth@v0'
#        with:
#          credentials_json: ${{ secrets.GOOGLE_CLOUD_KEY }}
#
#      - name: Set current project
#        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}
#
##firebase-test-lab-account@sigma-libraries.iam.gserviceaccount.com:
##  Instrumented-tests:
##    name: Android tests running
##    runs-on: ubuntu-latest
##    steps:
##
##      - name: Checkout
##        uses: actions/checkout@v3
##
##      - name: Set up JDK 11
##        uses: actions/setup-java@v3
##        with:
##          java-version: '11'
##          distribution: 'adopt'
##
##      - name: Run Android tests
##        uses: reactivecircus/android-emulator-runner@v2
##        with:
##          api-level: 29
##          arch: x86_64
##          script: ./gradlew connectedCheck
